-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Jeu 26 Octobre 2017 à 13:53
-- Version du serveur :  5.7.19-0ubuntu0.16.04.1
-- Version de PHP :  7.0.22-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `simple-mvc`
--

-- --------------------------------------------------------

--
-- Structure de la table `item`
--

CREATE TABLE `item` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `item`
--

INSERT INTO `item` (`id`, `title`) VALUES
(1, 'Stuff'),
(2, 'Doodads');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `item`
--
ALTER TABLE `item`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `item`
--
ALTER TABLE `item`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

CREATE TABLE `card` (
  `id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` VARCHAR(285) NOT NULL,
  `price` VARCHAR(30),
  `image` VARCHAR(255),
  `country` VARCHAR(50),
  `presentation` TEXT,
  `try` TEXT,
  `situation` TEXT,
  `location` TEXT,
  `animation` TEXT
);

INSERT INTO `card` (`title`, `description`, `price`, `image`, `country`, `presentation`, `situation`, `location`) VALUES
("Séjour en Ukraine", 
"Venez prouver votre amour du Kremlin en défilant fièrement dans les rues de Kiev et connaître une mort digne des plus grands pontes de l'ère soviétique.",
"500,00€",
"ukraine.webp",
"Ukraine",
"L'Ukraine, une nation captivante et riche d'histoire, offre un mélange envoûtant de cultures, de paysages et de traditions. Du majestueux Carpathes aux charmes de Kyiv, sa capitale animée, chaque coin de ce pays vous émerveillera. Découvrez ses monuments historiques, sa cuisine délicieuse et son peuple chaleureux. Plongez-vous dans la magie envoûtante de l'Ukraine.",
"La vie en Ukraine est marquée par une riche culture imprégnée de traditions, de musique et de cuisine. Les Ukrainiens sont connus pour leur hospitalité chaleureuse et leur attachement profond à leurs valeurs familiales. La culture ukrainienne célèbre la danse, le folklore et l'artisanat traditionnel, comme la broderie et la poterie. La musique folklorique ukrainienne, avec ses chants mélodiques et ses instruments traditionnels, est un élément central de l'identité culturelle du pays. La cuisine ukrainienne est copieuse et savoureuse, mettant en valeur des plats tels que le bortsch, les varenyky (pâtes farcies) et le salo (graisse de porc). Les fêtes traditionnelles, telles que le Nouvel An ukrainien et le festival de Pâques, sont célébrées avec enthousiasme et joie. L'Ukraine est également fière de son héritage littéraire, avec des écrivains renommés tels que Taras Shevchenko et Ivan Franko.",
"Bienvenue dans le monde merveilleux du logement basique ukrainien ! Imaginez une petite boîte carrée, appelée 'khrushchyovka', avec des murs si fins que vous pouvez entendre vos voisins faire leurs exercices de yoga matinaux... ou leurs disputes conjugales enflammées. Les fenêtres sont d'une simplicité charmante, avec un seul vitrage qui laisse passer le froid hivernal pour vous rappeler que vous êtes vivant. La salle de bain est une aventure en soi, avec une douche minuscule qui vous oblige à pratiquer le yoga de la contorsion pour vous laver correctement. L'eau chaude est un luxe rare, alors attendez-vous à des douches express glaciales qui vous rappellent que la vie est courte et pleine de surprises désagréables. La cuisine ? Eh bien, préparez-vous à devenir un chef créatif avec des plaques de cuisson qui fonctionnent au ralenti, un réfrigérateur qui ressemble à un congélateur et un évier qui fuit avec une joie débordante. Mais ne vous inquiétez pas, le logement basique ukrainien a aussi son charme. Les voisins deviendront rapidement votre famille élargie, vous partagerez des anecdotes sur les pannes d'électricité, les fuites d'eau et les visites surprises des rats de quartier. Et lorsque vous survivrez à tout cela, vous pourrez vous vanter d'avoir survécu à l'expérience de vie la plus hilarante et excentrique en Ukraine. Bonne chance !"
),
("Road-trip au Bengladesh en période de mousson",
"Soyez quelqu'un d'original en vous noyant sous des milliers de mètres cube d'eau de pluie au coeur de la capitale des catastrophes naturelles.",
"900,00€",
"bengladesh.webp",
"Bengladesh",
"Le Bangladesh, un pays vibrant et plein de surprises, vous invite à une expérience inoubliable. Explorez ses paysages luxuriants, des rizières infinies aux plages tropicales immaculées. Découvrez une riche histoire et une culture fascinante, imprégnée de traditions et d'hospitalité chaleureuse. Savourez sa cuisine délicieuse et échangez avec des gens accueillants. Le Bangladesh vous promet une aventure unique et enrichissante.",
"La vie au Bangladesh est imprégnée d'une culture vibrante et d'une riche histoire. Les Bangladeshis sont connus pour leur hospitalité chaleureuse et leur sens de la communauté. La culture bangladaise se reflète dans sa musique traditionnelle, comme le folk et le Baul, ainsi que dans ses danses colorées telles que le Jatra et le Bihu. La cuisine bangladaise est un véritable festin pour les sens, avec des plats épicés et savoureux tels que le biryani et le curry de poisson. Les festivals tels que Pohela Boishakh (Nouvel An bengali) et Durga Puja sont célébrés avec enthousiasme et joie. L'artisanat traditionnel du Bangladesh, comme la fabrication de tissus en soie et en jute, est également une part importante de la culture. Le pays a également produit des auteurs et des poètes renommés tels que Rabindranath Tagore.",
"Bienvenue dans le fabuleux monde des logements basiques au Bangladesh ! Imaginez une petite hutte en bambou, si humble qu'elle semble être faite de cure-dents et de rêves brisés. Les murs sont si fins que vous pouvez entendre le souffle du voisin et les pensées de sa grand-mère. La salle de bain est une aventure pleine de surprises. Vous pouvez profiter d'une douche en mode cascade grâce à un robinet qui fuit sans relâche. Et si vous avez de la chance, vous pourrez même vous baigner dans une charmante flaque d'eau de pluie qui a réussi à s'infiltrer par le toit. La cuisine est un terrain de jeu pour les amateurs de cuisine extrême. Les plaques de cuisson vous offrent un feu d'artifice culinaire, alternant entre incroyablement chaud et totalement éteint. Et pour couronner le tout, l'évier est un véritable maître en plomberie, avec des fuites d'eau créatives qui vous garantissent une expérience aquatique inoubliable. Mais ne vous inquiétez pas, dans ce logement basique du Bangladesh, vous découvrirez l'art de vivre minimaliste et la solidarité entre voisins. Vous partagerez des moments mémorables de frustration, de rires et de moustiques en échangeant des astuces pour survivre à la saison des pluies et à la chaleur étouffante. Alors, préparez-vous à une aventure immersive où chaque jour est une nouvelle leçon sur l'humilité et la résilience."
),
("Balade en Peugeot 3008 avec Pierre Palmade",
"Vous aimez la vitesse et l'adrénaline ? Vous les aimerez d'autant plus sous l'emprise de stupéfiants, accompagné d'un conducteur plein d'humour qui saura vous conduire directement au (septième) ciel.",
"20 000,00€",
"1200x768_l-acteur-pierre-palmade.png",
"Seine-et-Marne",
"La Seine-et-Marne, un département enchanteur aux portes de Paris, vous invite à une expérience mémorable. Découvrez ses paysages pittoresques, des châteaux majestueux aux forêts verdoyantes. Imprégnez-vous de son riche patrimoine historique et culturel, de ses villages charmants et de sa gastronomie savoureuse. Plongez-vous dans l'atmosphère unique de la Seine-et-Marne et laissez-vous séduire par son charme intemporel.",
"La vie en Seine-et-Marne, département situé en région Île-de-France, offre un cadre de vie riche en diversité et en charme. Les habitants de la Seine-et-Marne sont réputés pour leur convivialité et leur sens de la communauté. La culture locale se reflète dans la musique, les festivals et les événements culturels organisés tout au long de l'année. La gastronomie est également mise à l'honneur, avec des spécialités culinaires régionales telles que le brie de Meaux et le Coulommiers. Les paysages variés de la Seine-et-Marne, comprenant des forêts, des rivières et des châteaux historiques, offrent de nombreuses possibilités de loisirs et de découvertes. Les festivals et les marchés locaux sont des moments privilégiés pour partager la joie de vivre et l'authenticité de la région.",
"Bienvenue dans l'univers palpitant des logements basiques en Seine-et-Marne ! Imaginez une charmante maisonnette en banlieue, où les murs semblent avoir été décorés par des artistes amateurs à l'aide d'un assortiment aléatoire de couleurs douteuses. L'isolation ? Un concept purement théorique, car vous pouvez sentir le froid hivernal s'infiltrer à travers chaque fissure et recoin. La salle de bain est un voyage dans le temps, avec des carreaux vintage qui vous donnent l'impression de vivre dans un film des années 70. La baignoire est un véritable trésor de bricolage, avec un système de drainage aléatoire qui vous invite à une expérience aquatique inattendue à chaque utilisation. La cuisine est un défi culinaire où la créativité est de mise. Les plaques de cuisson ont une personnalité chaotique, oscillant entre une cuisson insuffisante et une chaleur infernale. Et ne vous inquiétez pas, l'évier est un véritable cascadeur, capable de vous surprendre avec des fuites d'eau dignes d'une scène d'action hollywoodienne. Mais ne vous laissez pas décourager ! En Seine-et-Marne, vous découvrirez l'art de la débrouillardise et la convivialité des voisins. Vous partagerez des moments de désespoir et de rires autour d'un bon verre de vin local, en échangeant des astuces pour naviguer dans les embouteillages incessants sur la route et pour survivre aux caprices de la météo. Alors, préparez-vous à une aventure pleine de charme, de surprises et de rencontres inoubliables dans le merveilleux monde des logements basiques en Seine-et-Marne !"
),
("Une nuit au quartier populaire de San Salvador",
"Vous n'aurez jamais eu autant de choix dans la manière de rendre votre dernier souffle, grâce à la créativité sans limites de jeunes chômeurs, enfants du pays où vivre au-delà de 30 ans est un exploit en soi.",
"900,00€",
"gang1-3457419823.png",
"El Salavdor",
"El Salvador, un pays vibrant et captivant d'Amérique centrale, vous invite à une expérience inoubliable. Découvrez ses plages spectaculaires, des vagues parfaites pour le surf aux eaux turquoise cristallines. Imprégnez-vous de son riche patrimoine précolombien et de sa culture vivante. Rencontrez des gens chaleureux et explorez des volcans majestueux. Laissez-vous séduire par la beauté naturelle et l'authenticité d'El Salvador.",
"La vie au Salvador, un pays d'Amérique centrale, est animée par une culture vibrante et une population chaleureuse. Les Salvadoriens sont connus pour leur hospitalité et leur esprit communautaire. La culture salvadorienne se reflète dans la musique traditionnelle, telle que le cumbia et le merengue, ainsi que dans les danses folkloriques colorées, comme le Xuc, le Són de la Negra et le Danzón. La cuisine salvadorienne est délicieuse et variée, mettant en avant des plats emblématiques tels que les pupusas, les yuca frita et les horchatas. Les fêtes traditionnelles, comme le carnaval de San Miguel et la Semaine sainte, sont célébrées avec passion et ferveur. L'artisanat salvadorien, notamment la poterie et les textiles, est réputé pour sa beauté et son artisanat habile. Le Salvador est également fier de son héritage littéraire, avec des écrivains talentueux comme Roque Dalton.",
"Bienvenue dans le monde exaltant des logements basiques au Salvador ! Imaginez une petite maison colorée, où les murs semblent avoir été peints par un artiste ayant un penchant pour les couleurs vives et audacieuses. L'isolation ? Eh bien, disons que les bruits de vos voisins font partie intégrante de votre vie sociale. La salle de bain est une aventure en soi, avec une douche qui joue à cache-cache avec la pression de l'eau. Attendez-vous à des moments de suspense alors que vous essayez de régler la température idéale tout en évitant les jets d'eau imprévisibles. La cuisine est un terrain de jeu culinaire où la flexibilité est de mise. Les plaques de cuisson sont de véritables acrobates, passant d'une chaleur ardente à une chaleur languissante en un clin d'œil. Et si vous aimez les défis, vous apprécierez les énigmes complexes posées par l'évier qui décide de se boucher aux moments les plus inopportuns. Mais ne vous inquiétez pas, au Salvador, vous découvrirez la chaleur humaine et la joie de vivre de ses habitants. Vous partagerez des moments de rires, de fêtes et de convivialité autour d'un délicieux plat de pupusas, la spécialité locale. Et lorsque les difficultés surviennent, vous serez soutenu par une communauté qui se serre les coudes. Alors, préparez-vous à vivre une expérience unique dans les logements basiques du Salvador, où chaque jour apporte son lot d'aventures, de couleurs et de rencontres authentiques."
),
("Stage en cellule d'isolement avec la BRAV-M",
"Au plus près de chez vous, au plus près du peuple, vous vous sentirez fier et patriote de voir votre heure venir sous les matraques endiablées de nos chers gardiens de la paix.",
"135,00€",
"BRAV-M.png",
"France",
"La France, un pays emblématique et raffiné, vous accueille avec élégance et charme. Découvrez ses trésors culturels, des somptueux châteaux de la Loire aux musées mondialement célèbres de Paris. Savourez sa cuisine exquise, ses vins renommés et son art de vivre. De la beauté de la Côte d'Azur aux paysages pittoresques de la Provence, laissez-vous séduire par la diversité et l'histoire fascinante de la France.",
"La vie en France, un pays emblématique et raffiné, offre une expérience unique et diversifiée. Les Français sont réputés pour leur passion pour l'art de vivre, la gastronomie et la culture. La culture française se manifeste à travers la musique, la littérature, le cinéma et la mode. Des festivals culturels, des expositions d'art et des spectacles captivants ont lieu dans tout le pays. La cuisine française est renommée mondialement, avec ses délicieux fromages, ses pâtisseries exquises et ses vins fins. Les régions françaises offrent des paysages variés, allant des montagnes alpines aux plages de la Côte d'Azur. Les Français sont fiers de leur patrimoine historique, avec des monuments emblématiques tels que la Tour Eiffel, le Louvre et le château de Versailles. La vie en France est ponctuée de festivals animés, de marchés pittoresques et de moments de détente dans les cafés et les parcs. La France est un pays qui célèbre l'art de vivre et offre une richesse culturelle inégalée.",
"Bienvenue dans l'univers captivant des logements basiques en France ! Imaginez une petite appartement typiquement parisien, où les murs semblent témoigner des nombreuses vies qui les ont précédés, avec des couches de peinture écaillée qui révèlent les histoires du passé. L'isolation ? Une source constante de surprises, car vous pouvez sentir le froid hivernal se faufiler à travers les fenêtres et les courants d'air vous rappeler que l'été est un luxe éphémère. La salle de bain est un défi artistique, avec une douche minuscule qui vous invite à des contorsions dignes d'un numéro de cirque pour vous laver. Vous pouvez également apprécier les charmes d'une plomberie capricieuse, où la température de l'eau est un mystère à résoudre à chaque utilisation. La cuisine est un terrain de jeu culinaire où la créativité est de mise. Les plaques de cuisson ont un esprit indépendant, passant de feux brûlants à des flammes vacillantes en un clin d'œil. Et l'évier ? Préparez-vous à devenir un expert en jonglerie avec des casseroles et des poêles pour éviter les fuites d'eau soudaines et les éclaboussures inattendues. Mais ne vous inquiétez pas, en France, vous découvrirez l'art de vivre et le plaisir des petites choses de la vie. Vous partagerez des moments de convivialité autour d'un bon verre de vin, en dégustant de délicieux fromages et en célébrant la richesse de la gastronomie française. Et lorsque vous traverserez des difficultés, vous serez entouré d'une communauté qui sait apprécier les plaisirs simples et qui valorise les liens humains. Alors, préparez-vous à une aventure pleine de charme, de saveurs et de découvertes dans les logements basiques en France, où chaque jour est une invitation à embrasser la beauté imparfaite de la vie."
),
("Descente des Chutes du Niagara en kanoë-kayak",
"C'est à faire au moins une fois dans une vie, par chance, c'est cette (dernière) fois que nous vous offrons avec notre habituelle amabilité, le gilet de sauvetage est en revanche à vos frais.",
"2 200,00€",
"68.jpg",
"Canada",
"Le Canada, un pays vaste et captivant, vous accueille avec une beauté naturelle époustouflante. Explorez ses majestueuses montagnes Rocheuses, ses vastes forêts et ses lacs cristallins. Imprégnez-vous de sa diversité culturelle et de sa tolérance. Découvrez des villes dynamiques telles que Toronto et Vancouver, et laissez-vous charmer par l'hospitalité chaleureuse des Canadiens. Le Canada vous promet une expérience inoubliable au cœur d'une nature préservée et d'une richesse culturelle.",
"Les Canadiens sont réputés pour leur gentillesse, leur ouverture d'esprit et leur accueil chaleureux. La culture canadienne est marquée par sa diversité, avec une fusion d'influences autochtones, britanniques, françaises et d'autres cultures du monde entier. La musique canadienne, le cinéma et la littérature ont une renommée internationale. La cuisine canadienne est variée, allant des plats traditionnels autochtones aux délices poutine et aux célèbres sirops d'érable. Les paysages canadiens sont spectaculaires, des majestueuses montagnes Rocheuses aux vastes plaines des Prairies et aux magnifiques côtes de l'Atlantique et du Pacifique. Les Canadiens apprécient les activités de plein air, comme le ski, la randonnée et le canoë-kayak. Les festivals et les événements culturels animent les villes et les communautés tout au long de l'année. La vie au Canada offre un équilibre entre qualité de vie, nature préservée et diversité culturelle.",
"Bienvenue dans le monde fascinant des logements basiques au Canada ! Imaginez une maison en bois typique, où les murs semblent témoigner des saisons qui défilent avec des fissures qui laissent passer un peu de l'air frais canadien. L'isolation ? Un défi à la fois, car vous pouvez sentir le froid hivernal s'infiltrer à travers les fenêtres et les courants d'air vous rappeler que l'hiver est là pour rester. La salle de bain est une expérience unique, avec une douche qui vous offre une douche écossaise, alternant entre des moments de chaleur réconfortante et des jets d'eau glaciale pour réveiller vos sens. Et si vous avez de la chance, vous pourrez profiter d'une vue imprenable sur un paysage enneigé depuis la fenêtre. La cuisine est un terrain de jeu culinaire où l'esprit d'improvisation est essentiel. Les plaques de cuisson vous défieront avec leur réglage de chaleur capricieux, passant d'une cuisson trop lente à un gril intense en un rien de temps. Et préparez-vous à des moments de débrouillardise lorsque l'évier décide de se boucher juste avant un grand dîner. Mais ne vous inquiétez pas, au Canada, vous découvrirez l'art de la chaleur humaine et le sens de la communauté. Vous partagerez des moments chaleureux autour d'une tasse de sirop d'érable, en célébrant les plaisirs simples de la vie et en créant des liens avec vos voisins dans des moments de convivialité. Alors, préparez-vous à vivre une aventure empreinte de nature, de résilience et de solidarité dans les logements basiques au Canada, où chaque jour est une invitation à apprécier la beauté des grands espaces et la chaleur des gens qui vous entourent."
),
("Altercation verbale avec Kim Jong-Un",
"Vous détestez l'autorité ? Sautez sur l'occasion grâce à cette offre inédite et allez vomir votre aigreur sur l'un des hommes d'état les plus respectés au monde pour finir torturé, émasculé, écartelé, vous et votre arrogance occidentale.",
"5 000 000 KPW",
"coree-nord_1149433_1250x625.jpeg",
"Corée du Nord",
"La Corée du Nord, un pays mystérieux et méconnu, intrigue les voyageurs audacieux. Explorez ses paysages montagneux et préservés, tels que le mont Paektu et les chutes d'eau de Kumgangsan. Imprégnez-vous de son riche patrimoine historique et de sa culture unique. Rencontrez des habitants accueillants et découvrez une société complexe et fascinante. Bien que les voyages soient strictement encadrés, la Corée du Nord offre une expérience unique et énigmatique pour ceux qui osent s'y aventurer.",
"La vie en Corée du Nord, un pays hermétique et isolé, est marquée par une culture unique et un régime politique strict. Les Nord-Coréens sont connus pour leur patriotisme et leur dévouement à l'idéologie du Juche. La culture nord-coréenne est largement influencée par les traditions confucéennes et le culte de la personnalité entourant les dirigeants. La musique et la danse traditionnelles, ainsi que les performances artistiques, sont des éléments importants de la culture nationale. La cuisine nord-coréenne met l'accent sur les plats de riz, de nouilles et de légumes, accompagnés de kimchi fermenté. Les festivités nationales, telles que l'anniversaire de Kim Il-sung, sont célébrées avec ferveur. La vie quotidienne en Corée du Nord est strictement réglementée, avec une surveillance étroite de la population et des limitations sur les contacts avec l'extérieur. Les informations sur la vie réelle en Corée du Nord sont souvent limitées et sujettes à controverse.",
"Bienvenue dans le monde mystérieux des logements basiques en Corée du Nord ! Imaginez une petite maisonnette, où les murs semblent garder tous les secrets du régime. L'isolation ? Un concept rare, car vous pouvez sentir le froid mordant de l'hiver pénétrer chaque fissure, vous rappelant que le confort est un luxe. La salle de bain est une expérience minimaliste, avec une douche qui offre des fluctuations aléatoires de température. Chaque jour est une surprise, car l'eau peut être soit glaciale, soit brûlante, ajoutant une dose d'aventure à votre routine quotidienne. La cuisine est un défi culinaire où la créativité est nécessaire. Les plaques de cuisson peuvent être imprévisibles, alternant entre une chaleur intense et une chaleur tiède, vous invitant à maîtriser l'art de la cuisson sur le vif. Et l'évier ? Il pourrait bien être votre meilleur ami ou votre pire ennemi, avec des fuites inattendues qui nécessitent une attention constante. Mais ne vous inquiétez pas, en Corée du Nord, vous découvrirez un esprit de communauté et une fierté nationale. Vous partagerez des moments de solidarité avec vos voisins, où le soutien mutuel est crucial dans un environnement complexe. Les repas partagés et les discussions animées vous permettront de ressentir la force et la résilience du peuple coréen. Alors, préparez-vous à une expérience unique dans les logements basiques en Corée du Nord, où chaque jour est une occasion de découvrir la culture, l'histoire et les défis d'une société complexe et souvent méconnue."
),
("Safari désertique en Tesla",
"Laissez la faune des brousses vous tenir compagnie après 400km de paysages époustouflants en pleine nature et savourez votre fin avec la classe d'un self-made man écoresponsable.",
"43 200,00€",
"Tesla-desert-Dubai-1.webp",
"Niger",
"Le Niger, un pays d'Afrique de l'Ouest, vous invite à découvrir sa beauté naturelle et sa richesse culturelle. Explorez ses vastes déserts et ses paysages contrastés, du Sahara aux montagnes de l'Aïr. Imprégnez-vous de son héritage historique, notamment à travers les anciennes cités de l'empire médiéval du Songhaï. Rencontrez des populations chaleureuses et accueillantes, découvrez leur artisanat traditionnel et délectez-vous de la gastronomie nigérienne. Le Niger vous promet une immersion authentique et une expérience inoubliable.",
"La vie au Niger, un pays d'Afrique de l'Ouest, est marquée par une riche culture et une histoire fascinante. Les Nigériens sont réputés pour leur hospitalité chaleureuse et leur sens de la communauté. La culture nigérienne est profondément enracinée dans les traditions et les coutumes, avec des danses et des chants traditionnels tels que le Takamba et le Bori. La cuisine nigérienne est variée et délicieuse, mettant en valeur des plats tels que le dambou (couscous de mil) et le fufu (pâte de mil). Les festivals traditionnels, tels que la Cure Salée et le Gerewol, offrent un aperçu coloré de la culture nigérienne. Les paysages du Niger, comprenant le désert du Sahara, des réserves naturelles et le fleuve Niger, offrent une beauté naturelle à couper le souffle. La vie quotidienne est rythmée par le commerce local, les marchés animés et les pratiques agricoles traditionnelles. Les Nigériens sont fiers de leur patrimoine historique, avec des sites archéologiques remarquables tels que les ruines de l'ancienne ville de Djado.",
"Bienvenue dans le monde authentique des logements basiques au Niger ! Imaginez une humble case en terre, où les murs témoignent de la riche culture et de la tradition ancestrale du pays. L'isolation ? Un concept presque inexistant, car vous pouvez sentir la chaleur du désert s'infiltrer à travers les interstices, rappelant que la nature est omniprésente. La salle de bain est une expérience de simplicité, avec un seau d'eau pour vous rafraîchir et une toilette à la turque pour vous accompagner dans vos moments intimes. Les éclaboussures d'eau et les moustiques ajoutent une dose d'aventure à cette routine quotidienne. La cuisine est un défi créatif, où les saveurs locales prennent vie. Les fours traditionnels vous invitent à maîtriser l'art de la cuisson sur feu de bois, tandis que les épices et les arômes transportent vos sens vers de nouveaux horizons gustatifs. Préparez-vous à des moments de partage et de convivialité autour d'un plat de riz ou de mil, accompagné de délicieux plats locaux. Mais ne vous inquiétez pas, au Niger, vous découvrirez l'hospitalité chaleureuse et la résilience du peuple nigérien. Vous partagerez des moments de solidarité, d'échange culturel et de célébration des traditions locales. Les chants, les danses et les récits traditionnels vous immergeront dans la richesse de la culture nigérienne. Alors, préparez-vous à vivre une expérience authentique dans les logements basiques au Niger, où chaque jour est une occasion de découvrir la beauté de la simplicité, de partager des moments précieux avec la communauté et de s'imprégner de la richesse culturelle du pays."
),
("Saut en parachute avec une serviette de bain",
"Votre rêve à vous, c'est de jouer les Inspecteurs Gadget devant tout le monde pour amuser la galerie. Ce rêve devient réalité en vous laissant l'opportunité de ne faire qu'un avec la terre après une descente riche en émotions et en fous rires. Petit farceur va!",
"250,00€",
"serviette.webp",
"Allemagne",
"L'Allemagne, un pays fascinant et riche en histoire, vous accueille avec une diversité culturelle et des paysages à couper le souffle. Explorez ses villes vibrantes, telles que Berlin, Munich et Hambourg, qui offrent une fusion unique d'histoire, d'art et de modernité. Imprégnez-vous de son patrimoine architectural, des châteaux romantiques aux cathédrales gothiques. Découvrez sa gastronomie renommée et sa tradition brassicole. Que ce soit pour sa musique, sa littérature ou son amour du sport, l'Allemagne vous offre une expérience passionnante et enrichissante à chaque coin de rue.",
"La vie en Allemagne, un pays dynamique et cosmopolite, offre une qualité de vie exceptionnelle et une riche diversité culturelle. Les Allemands sont connus pour leur rigueur, leur efficacité et leur sens du travail bien fait. La culture allemande est riche en traditions, en musique classique, en arts et en littérature, avec des figures emblématiques telles que Beethoven, Goethe et Bach. La cuisine allemande est variée et délicieuse, avec des plats typiques tels que les saucisses, les bretzels et la choucroute. Les festivals et les marchés de Noël traditionnels apportent une atmosphère festive tout au long de l'année. Les paysages allemands offrent une beauté naturelle, des forêts enchantées aux vignobles romantiques et aux châteaux médiévaux. Les Allemands attachent une grande importance à l'éducation, à la durabilité et aux sports, avec le football en tête. La vie quotidienne est marquée par des infrastructures modernes, des transports efficaces et une approche équilibrée du travail et des loisirs. L'Allemagne est un pays qui allie tradition et modernité, offrant une qualité de vie enviable et une diversité culturelle sans pareille.",
"Bienvenue dans le monde pratique des logements basiques en Allemagne ! Imaginez un appartement fonctionnel, où les murs reflètent l'efficacité et la rigueur allemandes. L'isolation ? Un concept bien maîtrisé, car vous pouvez profiter d'une température ambiante agréable, grâce à des fenêtres à double vitrage et une isolation thermique soignée. La salle de bain est une expérience de confort, avec une douche moderne et une attention particulière portée à l'hygiène. Vous pouvez vous attendre à des installations sanitaires impeccables et à une plomberie fiable, vous permettant de vous détendre et de vous rafraîchir en toute tranquillité. La cuisine est un terrain de créativité culinaire, où la fonctionnalité rencontre la précision. Les plaques de cuisson vous offrent un contrôle précis de la chaleur, tandis que les équipements modernes vous aident à préparer des repas délicieux avec facilité. Et grâce à des éviers bien conçus, vous pourrez faire la vaisselle sans effort et sans fuites indésirables. Mais ne vous inquiétez pas, en Allemagne, vous découvrirez également l'art de l'équilibre entre travail et plaisir. Vous pourrez partager des moments conviviaux autour d'une bière fraîche dans un Biergarten local ou vous immerger dans la culture riche et variée du pays. Les Allemands sont réputés pour leur ponctualité et leur sérieux, mais ils savent aussi profiter de la vie et faire la fête lors d'événements joyeux. Alors, préparez-vous à vivre une expérience pratique et confortable dans les logements basiques en Allemagne, où chaque jour est une occasion de découvrir la qualité de vie, l'organisation exemplaire et le charme subtil de ce pays fascinant."
),
("Excursion à la Castellane dans un bus du PSG",
"Votre amour pour le sport vous aura décidément suivi tout au long de votre vie et c'est sous le soleil radieux de la cité Phocéenne qu'elle se terminera en beauté, sous une pluie d'équipements électroménagers divers et d'ogives de 7.62x39.",
"100,00€",
"1200x680_maxstockworld403520.webp",
"France",
"La France, un pays emblématique et raffiné, vous accueille avec élégance et charme. Découvrez ses trésors culturels, des somptueux châteaux de la Loire aux musées mondialement célèbres de Paris. Savourez sa cuisine exquise, ses vins renommés et son art de vivre. De la beauté de la Côte d'Azur aux paysages pittoresques de la Provence, laissez-vous séduire par la diversité et l'histoire fascinante de la France.",
"La vie en France, un pays emblématique et raffiné, offre une expérience unique et diversifiée. Les Français sont réputés pour leur passion pour l'art de vivre, la gastronomie et la culture. La culture française se manifeste à travers la musique, la littérature, le cinéma et la mode. Des festivals culturels, des expositions d'art et des spectacles captivants ont lieu dans tout le pays. La cuisine française est renommée mondialement, avec ses délicieux fromages, ses pâtisseries exquises et ses vins fins. Les régions françaises offrent des paysages variés, allant des montagnes alpines aux plages de la Côte d'Azur. Les Français sont fiers de leur patrimoine historique, avec des monuments emblématiques tels que la Tour Eiffel, le Louvre et le château de Versailles. La vie en France est ponctuée de festivals animés, de marchés pittoresques et de moments de détente dans les cafés et les parcs. La France est un pays qui célèbre l'art de vivre et offre une richesse culturelle inégalée.",
"Bienvenue dans l'univers captivant des logements basiques en France ! Imaginez une petite appartement typiquement parisien, où les murs semblent témoigner des nombreuses vies qui les ont précédés, avec des couches de peinture écaillée qui révèlent les histoires du passé. L'isolation ? Une source constante de surprises, car vous pouvez sentir le froid hivernal se faufiler à travers les fenêtres et les courants d'air vous rappeler que l'été est un luxe éphémère. La salle de bain est un défi artistique, avec une douche minuscule qui vous invite à des contorsions dignes d'un numéro de cirque pour vous laver. Vous pouvez également apprécier les charmes d'une plomberie capricieuse, où la température de l'eau est un mystère à résoudre à chaque utilisation. La cuisine est un terrain de jeu culinaire où la créativité est de mise. Les plaques de cuisson ont un esprit indépendant, passant de feux brûlants à des flammes vacillantes en un clin d'œil. Et l'évier ? Préparez-vous à devenir un expert en jonglerie avec des casseroles et des poêles pour éviter les fuites d'eau soudaines et les éclaboussures inattendues. Mais ne vous inquiétez pas, en France, vous découvrirez l'art de vivre et le plaisir des petites choses de la vie. Vous partagerez des moments de convivialité autour d'un bon verre de vin, en dégustant de délicieux fromages et en célébrant la richesse de la gastronomie française. Et lorsque vous traverserez des difficultés, vous serez entouré d'une communauté qui sait apprécier les plaisirs simples et qui valorise les liens humains. Alors, préparez-vous à une aventure pleine de charme, de saveurs et de découvertes dans les logements basiques en France, où chaque jour est une invitation à embrasser la beauté imparfaite de la vie."
),
("Crémation par réacteur au prochain décollage de Space-X",
"Vous êtes un grand fan d'astronomie, de conquête spatiale, d'Elon Musk et ça vous va bien ! Vous êtes néanmoins quelqu'un de pressé et c'est pourquoi cette formule saura vous combler plus que n'importe qui d'autre en vous laissant partir en fumée tel David Copperfield.",
"30 000,00€",
"heavy.webp",
"USA",
"culturelle et des paysages à couper le souffle. Explorez ses villes emblématiques, de New York à Los Angeles, qui vibrent au rythme de la modernité et de la créativité. Imprégnez-vous de son patrimoine historique, des monuments emblématiques de Washington D.C. aux trésors naturels du Grand Canyon. Découvrez sa cuisine variée, ses parcs nationaux majestueux et son melting-pot culturel. Les États-Unis vous promettent une expérience inoubliable à chaque coin de rue.",
"La vie aux États-Unis, un pays vaste et diversifié, offre une expérience riche en opportunités et en diversité culturelle. Les Américains sont connus pour leur esprit d'entreprise, leur ouverture d'esprit et leur diversité. La culture américaine se manifeste à travers sa musique, son cinéma, sa littérature et sa cuisine, reflétant les nombreuses influences qui ont façonné le pays. La cuisine américaine est variée, allant des hamburgers et hot dogs emblématiques aux plats régionaux tels que les tacos, les pizzas et les crevettes du sud. Les Américains célèbrent leurs traditions lors de festivals et de rassemblements culturels, allant du Mardi Gras à la Fête de l'Indépendance. Les paysages américains sont époustouflants, des gratte-ciels de New York aux parcs nationaux majestueux tels que le Grand Canyon et le parc national de Yellowstone. Les Américains sont passionnés par le sport, avec des ligues professionnelles renommées dans le football américain, le basketball et le baseball. La vie quotidienne est dynamique, avec des villes animées, des centres commerciaux, des parcs d'attractions et une multitude d'activités de loisirs. Les États-Unis offrent une expérience de vie diversifiée et une multitude d'opportunités pour réaliser ses rêves.",
"Bienvenue dans l'univers déjanté des logements basiques américains ! Imaginez un appartement typique, où les murs semblent cacher les secrets de ses anciens occupants et où les dépanneurs de quartier sont plus nombreux que les étoiles dans le ciel. L'isolation ? Disons que vous pouvez entendre les voisins discuter de leurs problèmes conjugaux comme si vous étiez invité à leur thérapie de couple hebdomadaire. Parfois, vous pouvez même profiter d'un concert de tapage nocturne organisé par les jeunes artistes qui s'entraînent à jouer de la batterie dans leur garage. La salle de bain est une aventure en soi, avec une douche qui vous offre un choix exaltant entre des jets d'eau glaciaux ou des torrents brûlants dignes des enfers. Et si vous avez un peu de chance, vous pourrez profiter d'un spectacle de danse des toilettes qui se mettent à trembler sans raison apparente. La cuisine est un terrain de jeu gastronomique où vous pourrez tester vos talents de chef. Les plaques de cuisson, à la fois capricieuses et impulsives, décident de brûler vos aliments à une vitesse vertigineuse ou de les laisser crus comme s'ils venaient d'être récoltés. Et l'évier ? Préparez-vous à vivre une expérience aquatique étonnante avec des fuites d'eau surprises et des tuyaux qui se bouchent au moment où vous en avez le plus besoin. Mais ne vous inquiétez pas, aux États-Unis, vous découvrirez une énergie débordante et un sens de l'humour indomptable. Vous partagerez des moments de rires et de conversations animées avec vos voisins, qui peuvent avoir plus d'histoires folles à raconter que tous les épisodes de la télé-réalité américaine réunis. Alors, préparez-vous à une aventure chaotique et hilarante dans les logements basiques américains, où chaque jour est une occasion de vous demander ce qui vous attendra à votre retour à la maison. Après tout, la vie est trop courte pour être ennuyeuse, n'est-ce pas ?"
),
("Descente en tyrolienne sur une ligne à haute tension.",
"Vous êtes un peu un mélange de Johnny Halliday et Claude François, le théatral, ça vous parle et vous avez le goût du risque. Alors n'attendez plus pour venir profiter de notre accrobranche sur mesure pour ceux qui, comme vous, préfèrent une éternité sous les ifs à un lundi au soleil.",
"700€ (frais d'EDF compris)",
"cover-r4x3w1000.jpg",
"France",
"La France, un pays emblématique et raffiné, vous accueille avec élégance et charme. Découvrez ses trésors culturels, des somptueux châteaux de la Loire aux musées mondialement célèbres de Paris. Savourez sa cuisine exquise, ses vins renommés et son art de vivre. De la beauté de la Côte d'Azur aux paysages pittoresques de la Provence, laissez-vous séduire par la diversité et l'histoire fascinante de la France.",
"La vie en France, un pays emblématique et raffiné, offre une expérience unique et diversifiée. Les Français sont réputés pour leur passion pour l'art de vivre, la gastronomie et la culture. La culture française se manifeste à travers la musique, la littérature, le cinéma et la mode. Des festivals culturels, des expositions d'art et des spectacles captivants ont lieu dans tout le pays. La cuisine française est renommée mondialement, avec ses délicieux fromages, ses pâtisseries exquises et ses vins fins. Les régions françaises offrent des paysages variés, allant des montagnes alpines aux plages de la Côte d'Azur. Les Français sont fiers de leur patrimoine historique, avec des monuments emblématiques tels que la Tour Eiffel, le Louvre et le château de Versailles. La vie en France est ponctuée de festivals animés, de marchés pittoresques et de moments de détente dans les cafés et les parcs. La France est un pays qui célèbre l'art de vivre et offre une richesse culturelle inégalée.",
"Bienvenue dans l'univers captivant des logements basiques en France ! Imaginez une petite appartement typiquement parisien, où les murs semblent témoigner des nombreuses vies qui les ont précédés, avec des couches de peinture écaillée qui révèlent les histoires du passé. L'isolation ? Une source constante de surprises, car vous pouvez sentir le froid hivernal se faufiler à travers les fenêtres et les courants d'air vous rappeler que l'été est un luxe éphémère. La salle de bain est un défi artistique, avec une douche minuscule qui vous invite à des contorsions dignes d'un numéro de cirque pour vous laver. Vous pouvez également apprécier les charmes d'une plomberie capricieuse, où la température de l'eau est un mystère à résoudre à chaque utilisation. La cuisine est un terrain de jeu culinaire où la créativité est de mise. Les plaques de cuisson ont un esprit indépendant, passant de feux brûlants à des flammes vacillantes en un clin d'œil. Et l'évier ? Préparez-vous à devenir un expert en jonglerie avec des casseroles et des poêles pour éviter les fuites d'eau soudaines et les éclaboussures inattendues. Mais ne vous inquiétez pas, en France, vous découvrirez l'art de vivre et le plaisir des petites choses de la vie. Vous partagerez des moments de convivialité autour d'un bon verre de vin, en dégustant de délicieux fromages et en célébrant la richesse de la gastronomie française. Et lorsque vous traverserez des difficultés, vous serez entouré d'une communauté qui sait apprécier les plaisirs simples et qui valorise les liens humains. Alors, préparez-vous à une aventure pleine de charme, de saveurs et de découvertes dans les logements basiques en France, où chaque jour est une invitation à embrasser la beauté imparfaite de la vie."
);
